@startuml
'https://plantuml.com/activity-diagram-beta

start

:User accesses "/reports" page;
fork
:Show loading UI;
fork again
:Fetch HTML & CSS from server;
fork again
:Fetch organization reports data;
end fork
:Hydrate page with previously created reports data;

stop

@enduml
