@startuml
actor User

participant UI
participant System
participant DB

User -> UI: Click edit on ingredient in "/ingredient" page
UI -> User: redirects user to "/ingredient/{ingredientID}/edit"
User -> UI: Fills out form on what to edit
UI -> System: Submits & parses form data
System -> DB: Update ingredient instance
DB -> System: return ingredient data

System -> UI: Send Updated HTML, CSS, Inventory Data
UI -> User: Redirect to "/ingredient" & show HTML table of all ingredients

@enduml